\set s1 random(1, 3000)
\set s2 random(1, 3000)
\set s3 random(1, 3000)
\set s4 random(1, 3000)
\set s5 random(1, 3000)
\set s6 random(1, 3000)
\set s7 random(1, 3000)
\set s8 random(1, 3000)
\set s9 random(1, 3000)
\set s10 random(1, 3000)
\set s11 random(1, 3000)
\set s12 random(1, 3000)
\set s13 random(1, 3000)
\set s14 random(1, 3000)
\set s15 random(1, 3000)
\set s16 random(1, 3000)
\set s17 random(1, 3000)
\set s18 random(1, 3000)
\set s19 random(1, 3000)
\set s20 random(1, 3000)
SELECT c.id, c.pipeline_id, c.client_state, c.stop_requested_at, c.stopped_at, COALESCE(p.status, 'missing') AS pipeline_status FROM webhook_channels c LEFT JOIN pipelines p ON p.id = c.pipeline_id AND p.tenant_id = c.tenant_id WHERE c.provider = 'microsoft' AND c.provider_subscription_id = ANY(ARRAY['sub-' || :s1,'sub-' || :s2,'sub-' || :s3,'sub-' || :s4,'sub-' || :s5,'sub-' || :s6,'sub-' || :s7,'sub-' || :s8,'sub-' || :s9,'sub-' || :s10,'sub-' || :s11,'sub-' || :s12,'sub-' || :s13,'sub-' || :s14,'sub-' || :s15,'sub-' || :s16,'sub-' || :s17,'sub-' || :s18,'sub-' || :s19,'sub-' || :s20]);
INSERT INTO job_queue (tenant_id, kind, dedupe_key, payload, run_at) SELECT DISTINCT ON (t.kind, t.dedupe_key) t.tenant_id, t.kind, t.dedupe_key, t.payload, now() + (t.delay_ms * interval '1 millisecond') FROM unnest(ARRAY['acme','acme','acme','acme','acme','acme','acme','acme','acme','acme','acme','acme','acme','acme','acme','acme','acme','acme','acme','acme']::text[], ARRAY['pipeline.delta_sync','pipeline.delta_sync','pipeline.delta_sync','pipeline.delta_sync','pipeline.delta_sync','pipeline.delta_sync','pipeline.delta_sync','pipeline.delta_sync','pipeline.delta_sync','pipeline.delta_sync','pipeline.delta_sync','pipeline.delta_sync','pipeline.delta_sync','pipeline.delta_sync','pipeline.delta_sync','pipeline.delta_sync','pipeline.delta_sync','pipeline.delta_sync','pipeline.delta_sync','pipeline.delta_sync']::text[], ARRAY['delta:p' || :s1,'delta:p' || :s2,'delta:p' || :s3,'delta:p' || :s4,'delta:p' || :s5,'delta:p' || :s6,'delta:p' || :s7,'delta:p' || :s8,'delta:p' || :s9,'delta:p' || :s10,'delta:p' || :s11,'delta:p' || :s12,'delta:p' || :s13,'delta:p' || :s14,'delta:p' || :s15,'delta:p' || :s16,'delta:p' || :s17,'delta:p' || :s18,'delta:p' || :s19,'delta:p' || :s20]::text[], ARRAY[('{"pipelineId":"p' || :s1 || '","full":false}'),('{"pipelineId":"p' || :s2 || '","full":false}'),('{"pipelineId":"p' || :s3 || '","full":false}'),('{"pipelineId":"p' || :s4 || '","full":false}'),('{"pipelineId":"p' || :s5 || '","full":false}'),('{"pipelineId":"p' || :s6 || '","full":false}'),('{"pipelineId":"p' || :s7 || '","full":false}'),('{"pipelineId":"p' || :s8 || '","full":false}'),('{"pipelineId":"p' || :s9 || '","full":false}'),('{"pipelineId":"p' || :s10 || '","full":false}'),('{"pipelineId":"p' || :s11 || '","full":false}'),('{"pipelineId":"p' || :s12 || '","full":false}'),('{"pipelineId":"p' || :s13 || '","full":false}'),('{"pipelineId":"p' || :s14 || '","full":false}'),('{"pipelineId":"p' || :s15 || '","full":false}'),('{"pipelineId":"p' || :s16 || '","full":false}'),('{"pipelineId":"p' || :s17 || '","full":false}'),('{"pipelineId":"p' || :s18 || '","full":false}'),('{"pipelineId":"p' || :s19 || '","full":false}'),('{"pipelineId":"p' || :s20 || '","full":false}')]::jsonb[], ARRAY[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]::bigint[]) AS t(tenant_id, kind, dedupe_key, payload, delay_ms) ORDER BY t.kind, t.dedupe_key ON CONFLICT (kind, dedupe_key) WHERE status = 'queued' DO NOTHING;
